### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Mutualise CommitterRepository, add skipped test to implement, Inject appVersion in controller instead of getting from the global container, remove useless todo's
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Review by boherm — APPROVED** [review]
LGTM 👍

**Comment by matks** [comment]
@boherm @lartist Do we agree CI is enough to confirm this is working?

**Comment by lartist** [comment]
> @boherm @lartist Do we agree CI is enough to confirm this is working?

Hi @matks 
Currently there is no CI. I've just made a PR to process some check in CI. See https://github.com/PrestaShop/kanbanbot/pull/15

But I confirm we can merge it safely because I've run every tests in local and everything is ok !

**Comment by boherm** [comment]
Your work on the CI is merged.
If you want, you can rebase to have the CI running on this PR.

**Comment by boherm** [comment]
Thanks @lartist!

**Pull request merged**
